### ISSUE TITLE
Turkic UD project?

### ISSUE THREAD

**Issue by varie** [sigturk/sigturk#40]
There is a possibility to apply for funding. Cağrı Çöltekin mentioned about that at the meeting on 2022.11.21.

**Comment by varie** [comment]
COST Action

**Comment by mehmetoguzderin** [comment]
I think SIGTURK would be a great place to progress common understanding of concepts across Turkic languages through some task group or working group

**Comment by d-ataman** [comment]
We can port this discussion to the slack channel.

**Comment by mehmetoguzderin** [comment]
For word class standardization and annotation, @j0ma sent an interesting approach which might be relevant to our word class progress in future (for example, some Turkic languages split question marker some don't when annotating but it should converge): http://morpho.aalto.fi/projects/morpho/

**Comment by jonorthwash** [comment]
> We can port this discussion to the slack channel.

All your conversation are belong to Slack Technologies, LLC.

Could we get a Matrix bridge going?

**Comment by jonorthwash** [comment]
> For word class standardization and annotation, @j0ma sent an interesting approach which might be relevant to our word class progress in future (for example, some Turkic languages split question marker some don't when annotating but it should converge): http://morpho.aalto.fi/projects/morpho/

Could you direct us more specifically to the approach?  I'm having trouble finding anything Turkic-specific there.

**Comment by mehmetoguzderin** [comment]
@jonorthwash I'm also in support of installing the bridge (I've reserved the Matrix room and bridges just in case, but the last SIG call had only three participants so I couldn't bring up the bridging topic), but I have to admit that I didn't get why porting to Slack was even suggested when dialogue here is both easy to track and suitable for future reference purposes.

For reference I sent, in the call, we were (only casually) talking about morphology and how languages like English or Arabic change the "morph" of the word according to the features like tense or aspect (see, saw, etc.), and in contrast, how Turkic languages rather lack this mechanism (where exists, vowel harmony is purely phonetic than representing any semantic feature so excluding that phenomena) but rather pop things to end of the word, and @j0ma kindly pointed out this resource where project changes the impact of features to not reflect through a change in base morpheme but rather (according to my understanding as told in the meeting) gets represented as concatenations (producing a string similar to agglutinating morphemes). (Rest of this paragraph is just a discussion that spawns from that moment) Then we had a little chat about how we can not base word boundary on existing spelling rules as taught by governmental institutions due to cross-linguistic (within Turkic languages) inconsistency and, at times, political motivations to grow lexicon or distinguish parts with blank space for homophones but, instead try to reuse literature to have better word class definitions that align better across all natural languages and produce deeper trees.

Thank you!

**Comment by jonorthwash** [comment]
> languages like English or Arabic change the "morph" of the word according to the features like tense or aspect (see, saw, etc.), and in contrast, how Turkic languages rather lack this mechanism (where exists, vowel harmony is purely phonetic than representing any semantic feature so excluding that phenomena) but rather pop things to end of the word,

Your English example is "apophony", and Arabic has "introflection", whereas Turkic has concatenative affixation.  See my typology of these things at https://wikis.swarthmore.edu/ling073/Grammar_documentation#Common_morphological_strategies

> and @j0ma kindly pointed out this resource where project changes the impact of features to not reflect through a change in base morpheme but rather (according to my understanding as told in the meeting) gets represented as concatenations (producing a string similar to agglutinating morphemes).

If I understand right, this is how Apertium does it too.  In the case of Apertium, the structure is a lemma with tags following it (different types in a defined order).  See my explanation of Apertium tags here: https://wikis.swarthmore.edu/ling073/Grammar_documentation#Morphological_analyses

> we can not base word boundary on existing spelling rules as taught by governmental institutions due to cross-linguistic (within Turkic languages) inconsistency and, at times, political motivations to grow lexicon or distinguish parts with blank space for homophones but, instead try to reuse literature to have better word class definitions that align better across all natural languages and produce deeper trees.

As you know, tokenisation in Turkic is a problem we've discussed in various UD GitHub issues, including at least the following:
* https://github.com/UniversalDependencies/docs/issues/639
* https://github.com/UniversalDependencies/docs/issues/787
* https://github.com/UniversalDependencies/docs/issues/774
* https://github.com/UniversalDependencies/docs/issues/431

It's a tricky problem, and my thinking on it changes periodically :)

**Comment by mehmetoguzderin** [comment]
@jonorthwash thank you so much for kindly providing these pointers. That really provides content for this specific issue.

If I understand what I understand right when I convey my message before, it looks pretty overlapping (Apertium & the other resource)!

To be honest, I think it is a bit of an optimization problem.
1. Will the standards draw a line between etymology and not? For example, this is relevant in an auxiliary verb which today annotates its lemma as "i" in Modern Turkish but is not correct at all. But on the other hand, would you decompose "şimdi" to ş+im+di to produce the same syntactic tree as historical precedents of the language, given all words have clear traces in modern versions, and would constitute a closed class? Furthermore, borrowed words like "çünkü" (from Persian) could get a treatment like çün+ki because the borrowed grammatical element "ki" is productive in Modern Turkish and at the same time, it is in casual speech as "çün ki" quite often, but forcing dataset just to see "officially" (lol) lexicalized "çünkü" does not do justice (or reason).
2. Will the standards go bold to suggest ignoring word boundaries and maybe make them language-specific-feature-annotated data to recover "official" spelling? Placing the decision in this direction would allow for rational contemplation based on reasoning and discarding incorrect details.
3. For prefixes and suffixes in Turkic languages, given we are working on a scratch playground of code points with no blank space, how will the standards emerge their distinction from the syntactic element and morphological element in a cross-linguistically meaningful way? There are all kinds of precedents in Turkic languages when it comes to annotating a part as a "bound word" or part of the original word.

Turkic languages are not the only specimen that suffers from this. For example, in-the-affixation-sense-and-head-final typologically similar languages also go through bold decisions and new takes from scratch (some from their National Institutes, worthy of respect, see 国語研長単位に基づく日本語 Universal Dependencies at https://www.jstage.jst.go.jp/article/jnlp/30/1/30_4/_pdf PDF). Some of the questions have very deep implications. Still, the deep discussion & experimentation never took place, and different papers took different liberty with these aspects (with some going in the hinted direction, demonstrating better results with less computational complexity).

Appreciated!

**Comment by mehmetoguzderin** [comment]
There's an emerged on-going group about this, please do follow up with a more scoped issue if you'd like to see anything in conjunction with activities at SIGTURK. Thanks.
