### ISSUE TITLE
Hackathon

### ISSUE THREAD

**Issue by d-ataman** [sigturk/sigturk#96]
Discuss open-source platform developments and collaboration with MIT https://ktilana.wixsite.com/leshem-choshen/aboout

**Comment by mehmetoguzderin** [comment]
This event will be a great opportunity to finally bring the Core Guidelines vision into fruition by making the skeleton of a library to contain various functions through a standardized & reliable API (or the sketch of so).

I was pondering and maybe title should be rather "Hack Together" than Hackathon because we don't need the competition aspect IMO since we'll be providing a framework for people to experiment with

**Comment by mehmetoguzderin** [comment]
Closing since this issue is a duplicate of https://github.com/sigturk/sigturk/issues/94

Please do note any information you'd still like to see in the parent issue. Thanks
